name: Build
on:
  - push
  - workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: CHECKOUT REPOSITORY
        uses: actions/checkout@v7
      - name: SETUP JAVA JDK
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: BUILD
        uses: gradle/actions/setup-gradle@v6
        with:
          arguments: build
